version: "3"

services:
  server:
    build: .
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - database
    environment:
      POSTGRES_HOST: database
      POSTGRES_PORT: $POSTGRES_PORT
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      SLACK_OAUTH_TOKEN: $SLACK_OAUTH_TOKEN
      SLACK_SIGNING_SECRET: $SLACK_SIGNING_SECRET
      TRACK_WEEKS_DEFAULT: $TRACK_WEEKS_DEFAULT

  database:
    image: postgres:9.4
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - "db_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD

  caddy:
    image: caddy:2.3.0-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      CADDY_EMAIL: $CADDY_EMAIL
      CADDY_HOST: $CADDY_HOST
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile

volumes:
  db_data:
    driver: local
