version: "3"

services:
  server:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - database
    environment:
      POSTGRES_HOST: database
      POSTGRES_PORT: $POSTGRES_PORT
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      SLACK_OAUTH_TOKEN: $SLACK_OAUTH_TOKEN
      TRACK_WEEKS_DEFAULT: $TRACK_WEEKS_DEFAULT

  database:
    image: postgres:9.4
    ports:
      - 5432:5432
    volumes:
      - "db_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD

volumes:
  db_data:
    driver: local
